name             'jorani'
maintainer       'Learn Chef'
maintainer_email 'learnchef@chef.io'
license          'Apache 2.0'
description      'Installs and configures package httpd and sets a basic home page.'
long_description 'Installs and configures package httpd and sets a basic home page. This cookbook is used by the Learn Chef tutorials. https://learn.chef.io'
supports         'centos'
supports         'redhat'
version          '0.2.1'

# unpinned dependencies
depends 'apt'
depends 'php'
depends 'apache2'
depends 'zip'
depends 'git'
depends 'zipfile'
depends 'ark'
depends 'php5-mysql'
depends 'mysql'
