name             'jorani'
maintainer       'Learn Chef'
maintainer_email 'learnchef@chef.io'
license          'Apache 2.0'
description      'Installs and configures Jorani.'
long_description 'Installs and configures Jorani.'
supports         'Ubuntu'
version          '0.1'

# unpinned dependencies
depends 'apt'
depends 'php'
depends 'apache2'
depends 'zip'
depends 'git'
depends 'zipfile'
depends 'ark'
depends 'php5-mysql'
depends 'mysql'
